# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p packaging/rpm/SOURCES
          ls packaging/rpm/SOURCES
          tar --exclude='.git' --exclude='.gitignore' \
            --exclude='packaging/rpm/pkgs' --exclude='packaging/rpm/SOURCES' \
            -czvf packaging/rpm/SOURCES/${GITHUB_REPOSITORY#*/}-1.0.0.tar.gz \
            --transform="s/./${GITHUB_REPOSITORY#*/}-1.0.0/" ./
       
      - uses: Antikythera/build-rpm@v1
        id: build_rpm
        with:
          spec_file: packaging/rpm/redborder-kafka.spec
          sources: |
            packaging/rpm/SOURCES/${GITHUB_REPOSITORY#*/}-1.0.0.tar.gz
          variables: |
            _version=1.0.0
        
      

      - name: Check if service file exists
        run: ls ${{ github.workspace }}/resources/systemd/${GITHUB_REPOSITORY#*/}.service
